CREATE TABLE IF NOT EXISTS USER_INFO (
    USER_NUMBER bigint NOT NULL AUTO_INCREMENT,
    USER_NAME varchar(30) NOT NULL,
    USER_ID varchar(30) NOT NULL,
    PASSWORD varchar(32) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(USER_ID)
);